version: '3.1'

services:

  # Postgres official image:
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  # MongoDB official image:
  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Default web-GUI for Mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/